// frontend/js/recipeData.js
import { placeholderVideoEmbed } from './config.js'; // Ensure this path is correct

export const allRecipes = [
    {
        id: 'palak-paneer',
        title: 'Palak Paneer',
        image: 'https://beextravegant.com/wp-content/uploads/2021/08/Palak-paneer-7-edited.jpg',
        time: '40min',
        calories_text: '420 cal',
        rating: '4.8 ★',
        tags: ['Vegetarian', 'Indian'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['200g Paneer', '2 cups Spinach (Palak)', '1 Onion', '2 Tomatoes', 'Ginger-garlic paste', 'Spices (turmeric, cumin, coriander, garam masala)', 'Cream (optional)'],
        instructions: '1. Blanch spinach, then blend to a puree. 2. Sauté onions, ginger-garlic, tomatoes. Add spices. 3. Add spinach puree and paneer cubes. Simmer. 4. Finish with cream if desired. Serve hot.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/5lVLxEr_qgM?si=jH9ZZt2vWxtLkKNk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 420, protein: 20, carbs: 15, fats: 30 }
    },
    {
        id: 'chana-masala',
        title: 'Chana Masala',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShRpQcWVj2oxVVigAbnEWXbdNoIRGMmDScAA&s',
        time: '35min',
        calories_text: '380 cal',
        rating: '4.7 ★',
        tags: ['Vegetarian', 'Indian', 'Vegan'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['1 can Chickpeas (Chana)', '1 Onion', '2 Tomatoes', 'Ginger-garlic paste', 'Chana masala powder', 'Other spices (turmeric, chili powder)'],
        instructions: '1. Sauté onions, ginger-garlic, tomatoes. 2. Add chana masala powder and other spices. 3. Add boiled chickpeas and water. Simmer until gravy thickens. 4. Garnish with coriander. Serve with rice or roti.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/RXZsDHKlVGw?si=FSs64WCmUv39eFKD" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 380, protein: 15, carbs: 50, fats: 12 }
    },
    {
        id: 'veg-biryani',
        title: 'Vegetable Biryani',
        image: 'https://i0.wp.com/bhavnaskitchen.com/wp-content/uploads/2016/05/veg-biryani-in-pressure-cooker-61442869362-810.jpg?fit=810%2C537&ssl=1',
        time: '50min',
        calories_text: '450 cal',
        rating: '4.6 ★',
        tags: ['Vegetarian', 'Indian'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['1 cup Basmati Rice', 'Mixed Vegetables (carrots, peas, beans, potatoes)', 'Onion', 'Yogurt', 'Biryani masala', 'Whole spices (bay leaf, cardamom, cloves)'],
        instructions: '1. Sauté onions and whole spices. 2. Add vegetables, yogurt, and biryani masala. Cook for a few minutes. 3. Layer partially cooked rice and vegetable mixture. 4. Cook on low heat (dum) until rice is fully cooked. Serve hot.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/gYE9zOmJwsg?si=o3wWWibKYJyCZOUG" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 450, protein: 10, carbs: 70, fats: 15 }
    },
    {
        id: 'veg-salad',
        title: 'Vegetable Salad',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeVawhUT359g6S_0c2s4anpm6cwR2b1y7zsA&s',
        time: '15min',
        calories_text: '280 cal',
        rating: '4.3 ★',
        tags: ['Vegetarian', 'Vegan', 'Healthy'],
        mealType: ['Salad', 'Starter', 'Side Dish'],
        ingredients: ['Mixed Greens (lettuce, spinach)', 'Cucumber', 'Tomatoes', 'Carrots', 'Bell Peppers', 'Olive oil', 'Lemon juice', 'Salt', 'Pepper'],
        instructions: '1. Chop all vegetables. 2. Combine in a large bowl. 3. Whisk olive oil, lemon juice, salt, and pepper for dressing. 4. Pour dressing over salad and toss. Serve fresh.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/TKEgCMyU65Q?si=zcAgnAmtBn36H6N1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 280, protein: 5, carbs: 25, fats: 18 }
    },
    {
        id: 'buddha-bowl',
        title: 'Buddha Bowl',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTS6nMuZcjWwEobhQ86zaPudAZTapXOoeHVhg&s',
        time: '25min',
        calories_text: '350 cal',
        rating: '4.5 ★',
        tags: ['Vegetarian', 'Vegan', 'Healthy'],
        mealType: ['Lunch', 'Dinner', 'Main Course', 'Salad'],
        ingredients: ['Quinoa or Brown Rice (cooked)', 'Roasted Sweet Potatoes', 'Chickpeas', 'Avocado', 'Spinach', 'Tahini dressing'],
        instructions: '1. Arrange cooked grains in a bowl. 2. Top with roasted sweet potatoes, chickpeas, avocado slices, and spinach. 3. Drizzle with tahini dressing. Enjoy!',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/5grQyHO2-jw?si=7JKzba796rBI7_S6" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 350, protein: 12, carbs: 45, fats: 15 }
    },
    {
        id: 'quinoa-salad',
        title: 'Quinoa Salad',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSskOGZH7re6MT4iBXrXX6GEPwFgiMtDayqOQ&s',
        time: '20min',
        calories_text: '310 cal',
        rating: '4.4 ★',
        tags: ['Vegetarian', 'Vegan', 'Healthy', 'Gluten-Free'],
        mealType: ['Lunch', 'Salad', 'Side Dish'],
        ingredients: ['1 cup Cooked Quinoa', 'Cucumber', 'Bell Peppers (mixed colors)', 'Red Onion', 'Chickpeas', 'Feta cheese (optional)', 'Lemon-herb vinaigrette'],
        instructions: '1. Combine cooked quinoa with chopped vegetables and chickpeas in a bowl. 2. If using, add crumbled feta. 3. Drizzle with lemon-herb vinaigrette and toss to combine. Serve chilled or at room temperature.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/M7z_ABg8aqU?si=TEfMW05Nzzu8Rgwu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 310, protein: 10, carbs: 40, fats: 12 }
    },
    {
        id: 'ramen',
        title: 'Tonkotsu Ramen',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTid3WfMc-XNVLuFavhjM2iqU6asGN7fz6VLA&s",
        time: 'Long broth prep / 30min assembly',
        calories_text: '650 cal',
        rating: '4.8 ★',
        tags: ['Non-Vegetarian', 'Japanese'],
        mealType: ['Lunch', 'Dinner', 'Main Course', 'Soup'],
        ingredients: ['Pork bones (for broth)', 'Ramen noodles', 'Chashu pork', 'Soft-boiled egg', 'Nori', 'Scallions', 'Menma (bamboo shoots)'],
        instructions: 'Prepare rich pork broth (long process). Cook noodles. Assemble bowl with broth, noodles, and toppings.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/plTuwZva37k?si=Qw0JUM2YgX_WDBpr" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 650, protein: 30, carbs: 60, fats: 35 }
    },
    {
        id: 'moussaka',
        title: 'Moussaka',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQl_kAuSnthcisnhxtLKAktpp0nAz5w9oM0MQ&s",
        time: '1hr 30min',
        calories_text: '600 cal',
        rating: '4.7 ★',
        tags: ['Non-Vegetarian', 'Greek', 'Mediterranean'],
        mealType: ['Dinner', 'Main Course'],
        ingredients: ['Eggplant', 'Ground lamb/beef', 'Onion', 'Tomatoes', 'Cinnamon', 'Béchamel sauce', 'Potatoes (optional)'],
        instructions: 'Layer fried eggplant/potato, spiced meat sauce, and béchamel. Bake until golden and bubbly.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/Z_GcsR7Q99s?si=1BrprDZJ_RqJ9ugx" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 600, protein: 25, carbs: 40, fats: 38 }
    },
    {
        id: 'paella',
        title: 'Seafood Paella',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmbr-fTMhPF1vZ1w6cOKVIRREko05XZA5Buw&s",
        time: '1hr',
        calories_text: '700 cal',
        rating: '4.8 ★',
        tags: ['Seafood', 'Spanish'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Bomba rice', 'Shrimp', 'Mussels', 'Clams', 'Chicken/Rabbit (optional)', 'Saffron', 'Smoked paprika', 'Peas', 'Bell peppers'],
        instructions: 'Sauté aromatics, protein. Add rice, toast. Add broth, saffron, paprika. Arrange seafood on top. Cook uncovered until liquid absorbs and socarrat forms.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/vNBuXsTY15E?si=yqPpQNLNJmoiGnqX" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 700, protein: 40, carbs: 80, fats: 20 }
    },
    {
        id: 'butter-chicken',
        title: 'Butter Chicken (Murgh Makhani)',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpsLZxzy3tU_EncPMI44KcT4aGdFdGVtMxPw&s',
        time: '50min',
        calories_text: '550 cal',
        rating: '4.9 ★',
        tags: ['Non-Vegetarian', 'Indian'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['500g Chicken', 'Yogurt', 'Ginger-garlic paste', 'Tomato puree', 'Cream', 'Butter', 'Spices (Kashmiri chili, garam masala, kasuri methi)'],
        instructions: 'Marinate chicken. Grill or pan-fry. Prepare makhani gravy with tomato puree, butter, cream, and spices. Add chicken. Simmer. Serve hot.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/RKNogWbAivY?si=0A8fUAORmy55-nbU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 550, protein: 35, carbs: 20, fats: 38 }
    },
    {
        id: 'rogan-josh',
        title: 'Rogan Josh',
        image:'https://headbangerskitchen.com/wp-content/uploads/2024/08/ROGANJOSH-H2.jpg' ,
        time: '1hr 30min',
        calories_text: '480 cal',
        rating: '4.8 ★',
        tags: ['Non-Vegetarian', 'Indian', 'Kashmiri'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['500g Lamb/Mutton', 'Yogurt', 'Onions', 'Ginger-garlic paste', 'Whole spices', 'Kashmiri red chili powder', 'Fennel powder', 'Ginger powder'],
        instructions: 'Brown meat. Sauté onions, add spices and yogurt. Cook meat in the gravy until tender. Garnish with coriander.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/ZaZNZdehT0E?si=9xVjTBHQ-njbDCVw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 480, protein: 30, carbs: 15, fats: 32 }
    },
    {
        id: 'dal-makhani',
        title: 'Dal Makhani',
        image: 'https://myborosil.com/cdn/shop/articles/21.png',
        time: 'Overnight soak + 1hr',
        calories_text: '400 cal',
        rating: '4.9 ★',
        tags: ['Vegetarian', 'Indian', 'Punjabi'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Whole black lentils (urad dal)', 'Kidney beans (rajma)', 'Butter', 'Cream', 'Tomato puree', 'Ginger-garlic paste', 'Spices'],
        instructions: 'Soak lentils and beans. Pressure cook. Simmer with tomato puree, spices, butter, and cream until rich and creamy.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/mA5XjhdwJHc?si=8RD28bDquvyip1u6" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 400, protein: 18, carbs: 45, fats: 18 }
    },
    {
        id: 'malai-kofta',
        title: 'Malai Kofta',
        image: 'https://kitchenofdebjani.com/wp-content/uploads/2024/11/Paneer-Kofta-Recipe-Debjanir-Rannaghar.jpg',
        time: '1hr',
        calories_text: '520 cal',
        rating: '4.7 ★',
        tags: ['Vegetarian', 'Indian'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Paneer', 'Potatoes', 'Nuts', 'Cream', 'Onion-tomato gravy', 'Spices'],
        instructions: 'Make koftas from paneer, potatoes, nuts. Fry. Prepare a rich, creamy gravy. Add koftas just before serving.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/Tn1UeCKOACU?si=7OFqYGMFQoCsg1Rh" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 520, protein: 15, carbs: 30, fats: 40 }
    },
    {
        id: 'chicken-tikka-masala',
        title: 'Chicken Tikka Masala',
        image: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2022/06/chicken-tikka-masala.jpg',
        time: '1hr',
        calories_text: '500 cal',
        rating: '4.9 ★',
        tags: ['Non-Vegetarian', 'Indian', 'British-Indian'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Chicken tikka pieces', 'Onion-tomato based gravy', 'Cream', 'Yogurt', 'Spices (garam masala, paprika)'],
        instructions: 'Prepare chicken tikka. Make a creamy, spiced tomato gravy. Add chicken tikka pieces. Simmer and serve.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/wm5vqZcl8BQ?si=fDneSiKoQqOVLtBP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 500, protein: 30, carbs: 25, fats: 30 }
    },
    {
        id: 'paneer-butter-masala',
        title: 'Paneer Butter Masala',
        image: 'https://i0.wp.com/aartimadan.com/wp-content/uploads/2023/11/Paneer-Butter-Masala-Restaurant-Style.jpg?fit=800%2C449&ssl=1',
        time: '45min',
        calories_text: '480 cal',
        rating: '4.8 ★',
        tags: ['Vegetarian', 'Indian'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Paneer', 'Butter', 'Cream', 'Tomato puree', 'Onion', 'Cashews', 'Spices'],
        instructions: 'Make a smooth, rich gravy with tomatoes, onions, cashews, and spices. Add paneer cubes. Finish with butter and cream.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/a30BLUQiFoc?si=Cas8OCYraffnE8Hr" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 480, protein: 18, carbs: 20, fats: 35 }
    },
    {
        id: 'masala-dosa',
        title: 'Masala Dosa',
        image: 'https://i.ytimg.com/vi/CCab5oh0ZOc/maxresdefault.jpg',
        time: 'Fermentation + 30min',
        calories_text: '350 cal',
        rating: '4.9 ★',
        tags: ['Vegetarian', 'Indian', 'South Indian', 'Vegan Option'],
        mealType: ['Breakfast', 'Brunch', 'Lunch', 'Snack'],
        ingredients: ['Dosa batter (rice, urad dal)', 'Potatoes', 'Onion', 'Mustard seeds', 'Turmeric', 'Green chilies'],
        instructions: 'Prepare potato masala filling. Make thin crepes (dosas) from fermented batter. Fill with masala. Serve with sambar and chutney.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/PFG1aeYgi7c?si=mRRZAiwfogDQJ_2G" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 350, protein: 8, carbs: 60, fats: 10 }
    },
    {
        id: 'samosa',
        title: 'Samosa',
        image: 'https://c.ndtvimg.com/2023-03/0m65kep_samosa_625x300_10_March_23.jpg',
        time: '1hr',
        calories_text: '250 cal/piece',
        rating: '4.8 ★',
        tags: ['Vegetarian', 'Indian', 'Snack'],
        mealType: ['Starter', 'Snack', 'Street Food'],
        ingredients: ['All-purpose flour (maida)', 'Potatoes', 'Peas', 'Spices (cumin, coriander, amchoor)', 'Oil for frying'],
        instructions: 'Prepare dough. Make spiced potato and pea filling. Stuff dough cones, seal, and deep fry until golden brown.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/W0zDu1o74Uc?si=QgBZ7mFETa6EYrAt" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 250, protein: 4, carbs: 30, fats: 13 } // Per piece
    },
    {
        id: 'pav-bhaji',
        title: 'Pav Bhaji',
        image: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Bambayya_Pav_bhaji.jpg",
        time: '45min',
        calories_text: '400 cal',
        rating: '4.9 ★',
        tags: ['Vegetarian', 'Indian', 'Street Food'],
        mealType: ['Lunch', 'Dinner', 'Snack', 'Street Food'],
        ingredients: ['Mixed vegetables (potatoes, peas, cauliflower, carrots, capsicum)', 'Onions', 'Tomatoes', 'Pav bhaji masala', 'Butter', 'Pav (bread rolls)'],
        instructions: 'Boil and mash vegetables. Sauté onions, tomatoes, add pav bhaji masala and mashed vegetables. Simmer. Serve with buttered pav.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/gkH2eqFb_YE?si=vGM-vfdtQxI2gx_b" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 400, protein: 10, carbs: 55, fats: 15 }
    },
    {
        id: 'idli-sambar',
        title: 'Idli Sambar',
        image: "https://vaya.in/recipes/wp-content/uploads/2018/02/Idli-and-Sambar-1.jpg",
        time: 'Fermentation + 45min',
        calories_text: '300 cal',
        rating: '4.8 ★',
        tags: ['Vegetarian', 'Indian', 'South Indian', 'Vegan'],
        mealType: ['Breakfast', 'Brunch', 'Lunch'],
        ingredients: ['Idli batter (rice, urad dal)', 'For Sambar: Toor dal, mixed vegetables, tamarind pulp, sambar powder'],
        instructions: 'Steam idlis from fermented batter. Prepare sambar by cooking dal with vegetables, tamarind, and sambar powder. Serve hot.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/_QLLo1b5Zcw?si=j2aIAjgsALymt7gB" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 300, protein: 12, carbs: 58, fats: 2 }
    },
    {
        id: 'rajma-chawal',
        title: 'Rajma Chawal',
        image: 'https://www.kuchpakrahahai.in/wp-content/uploads/2023/05/Rajma-chawal.jpg',
        time: 'Soak + 1hr',
        calories_text: '450 cal',
        rating: '4.7 ★',
        tags: ['Vegetarian', 'Indian', 'Punjabi', 'Vegan Option'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Kidney beans (rajma)', 'Onion', 'Tomato', 'Ginger-garlic paste', 'Spices', 'Rice'],
        instructions: 'Soak and cook rajma. Prepare a spiced onion-tomato gravy. Add cooked rajma and simmer. Serve with steamed rice.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/M_ncAJhIaIU?si=nIfMmY2U5L6RYhY4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 450, protein: 18, carbs: 80, fats: 8 }
    },
    {
        id: 'gajar-halwa',
        title: 'Gajar Ka Halwa',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDa6Oz_axWLCnoKIfQkWJ-N4f9alvsT-H3vg&s",
        time: '1hr',
        calories_text: '350 cal',
        rating: '4.9 ★',
        tags: ['Vegetarian', 'Indian', 'Dessert'],
        mealType: ['Dessert'],
        ingredients: ['Carrots (grated)', 'Milk', 'Sugar', 'Ghee', 'Cardamom', 'Nuts (almonds, cashews)'],
        instructions: 'Cook grated carrots in milk until soft and milk reduces. Add sugar, ghee, cardamom. Cook until it thickens. Garnish with nuts.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/CNJBC-TJJTA?si=LlC-ec0UcMObvDzG" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 350, protein: 6, carbs: 50, fats: 15 }
    },
    {
        id: 'baingan-bharta',
        title: 'Baingan Bharta',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKhxoUaa1qKzeJCMnmUuK5dZ9hr3V8klxQOA&s",
        time: '50min',
        calories_text: '280 cal',
        rating: '4.6 ★',
        tags: ['Vegetarian', 'Indian', 'Vegan', 'Gluten-Free'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['1 large Eggplant (Baingan)', 'Onions', 'Tomatoes', 'Ginger-garlic paste', 'Green chilies', 'Coriander leaves', 'Spices (turmeric, cumin, coriander powder)'],
        instructions: 'Roast eggplant until skin is charred and flesh is soft. Peel and mash. Sauté onions, ginger-garlic, chilies, and tomatoes. Add spices and mashed eggplant. Cook well and garnish with coriander.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/yRZKfDI28Ro?si=HHFo1FoEoz661QiM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 280, protein: 5, carbs: 30, fats: 16 }
    },
    {
        id: 'matar-paneer',
        title: 'Matar Paneer',
        image: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/03/matar-paneer.jpg',
        time: '40min',
        calories_text: '430 cal',
        rating: '4.7 ★',
        tags: ['Vegetarian', 'Indian'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['200g Paneer (cubed)', '1 cup Green Peas (Matar)', 'Onions', 'Tomatoes', 'Ginger-garlic paste', 'Cream (optional)', 'Spices (turmeric, garam masala, coriander powder)'],
        instructions: 'Sauté onions, ginger-garlic, and tomato puree. Add spices. Add green peas and paneer. Simmer until peas are cooked and gravy thickens. Finish with cream if desired.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/tYt9s6-5MLc?si=TsiIzV5Y2lO3BIDU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 430, protein: 20, carbs: 25, fats: 28 }
    },
    {
        id: 'bhindi-masala',
        title: 'Bhindi Masala (Okra Fry)',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8RsKzKNlYjMYFbTjYV-pAPfzcFQhqFBK6UQ&s",
        time: '35min',
        calories_text: '250 cal',
        rating: '4.5 ★',
        tags: ['Vegetarian', 'Indian', 'Vegan'],
        mealType: ['Lunch', 'Dinner', 'Side Dish'],
        ingredients: ['250g Okra (Bhindi)', 'Onions', 'Tomatoes (optional)', 'Spices (turmeric, chili powder, amchoor/dry mango powder, coriander powder)'],
        instructions: 'Wash, dry, and chop okra. Sauté onions. Add okra and cook until tender-crisp. Add spices and tomatoes (if using). Cook for a few more minutes.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/UcEwOxVOOKU?si=jaEsuTDf30Tpkwm0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 250, protein: 4, carbs: 20, fats: 18 }
    },
    {
        id: 'dal-tadka',
        title: 'Dal Tadka',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTceME8iU7cw_7hAEFviIhZyYa8VpU_iZ-Sw&s',
        time: '30min',
        calories_text: '320 cal',
        rating: '4.7 ★',
        tags: ['Vegetarian', 'Indian', 'Vegan'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['1 cup Toor Dal (split pigeon peas)', 'Turmeric', 'Salt', 'For Tadka: Ghee/Oil, Cumin seeds, Mustard seeds, Dried red chilies, Asafoetida (hing), Garlic, Onion, Tomato'],
        instructions: '1. Pressure cook dal with turmeric and salt until soft. 2. For tadka, heat ghee/oil, add seeds, chilies, hing. Sauté garlic, onion, tomato. 3. Pour tadka over cooked dal. Mix well. Serve hot.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/8c_scYUN5uc?si=1A0ni8D-6sPBqOx-" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 320, protein: 14, carbs: 40, fats: 12 }
    },
    {
        id: 'aloo-gobi',
        title: 'Aloo Gobi',
        image: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/aloo-gobi-recipe.jpg',
        time: '35min',
        calories_text: '290 cal',
        rating: '4.6 ★',
        tags: ['Vegetarian', 'Indian', 'Vegan'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['2 Potatoes (Aloo), cubed', '1 head Cauliflower (Gobi), florets', 'Onion', 'Tomato', 'Ginger-garlic paste', 'Spices (turmeric, cumin, coriander, garam masala)'],
        instructions: '1. Sauté onions, ginger-garlic, tomato. 2. Add spices. 3. Add potatoes and cauliflower. Cook covered until tender, stirring occasionally. 4. Garnish with coriander. Serve with roti.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/KMVI7NHcbNE?si=xi-9GJ6ItM8qmThk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 290, protein: 6, carbs: 35, fats: 15 }
    },
    {
        id: 'chicken-korma',
        title: 'Chicken Korma',
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/08/chicken-korma-recipe.jpg",
        time: '1hr',
        calories_text: '520 cal',
        rating: '4.8 ★',
        tags: ['Non-Vegetarian', 'Indian'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['500g Chicken', 'Yogurt', 'Onion paste', 'Cashew/Almond paste', 'Ginger-garlic paste', 'Whole spices', 'Kewra water (optional)'],
        instructions: 'Marinate chicken. Sauté onion paste, ginger-garlic. Add chicken and cook. Add yogurt, nut paste, and spices. Simmer until chicken is tender and gravy is rich.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/Aj3xkvpEbFA?si=4j3601kGrxw6t1HL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 520, protein: 32, carbs: 18, fats: 35 }
    },
    {
        id: 'fish-curry',
        title: 'Goan Fish Curry',
        image: "https://www.chefkunalkapur.com/wp-content/uploads/2023/01/DSC08225-1300x731.jpg?v=1674579659",
        time: '45min',
        calories_text: '400 cal',
        rating: '4.7 ★',
        tags: ['Non-Vegetarian', 'Indian', 'Goan'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['500g Fish fillets (Kingfish/Pomfret)', 'Coconut milk', 'Onions', 'Tomatoes', 'Ginger-garlic paste', 'Tamarind pulp', 'Goan red masala (Recheado or similar)'],
        instructions: 'Marinate fish. Prepare curry base with onions, tomatoes, ginger-garlic, Goan masala, and coconut milk. Add tamarind pulp. Simmer fish in the curry until cooked.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/kEZWvkVeUOk?si=K1YSJXgle1rJOIKV" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 400, protein: 28, carbs: 15, fats: 25 }
    },
    {
        id: 'vegetable-pakora',
        title: 'Vegetable Pakora',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMqJHP80oDv4XoUOdOA53NOyD-7kpBWw6QUQ&s",
        time: '30min',
        calories_text: '300 cal (per serving)',
        rating: '4.6 ★',
        tags: ['Vegetarian', 'Indian', 'Snack', 'Vegan'],
        mealType: ['Starter', 'Snack'],
        ingredients: ['Mixed vegetables (onion, potato, spinach, cauliflower)', 'Gram flour (Besan)', 'Rice flour (for crispiness)', 'Spices (ajwain, turmeric, chili powder)', 'Oil for frying'],
        instructions: 'Slice vegetables. Make a thick batter with gram flour, rice flour, spices, and water. Dip vegetables in batter and deep fry until golden and crisp.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/ibzQobIsG4k?si=xfJSkxdeLNDpbrU_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 300, protein: 6, carbs: 25, fats: 20 } // per serving
    },
    {
        id: 'gulab-jamun',
        title: 'Gulab Jamun',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpridNzzU09HIIGpVPQ9XhWqay-q7NrMj1yg&s",
        time: '1hr',
        calories_text: '150 cal/piece',
        rating: '4.9 ★',
        tags: ['Vegetarian', 'Indian', 'Dessert'],
        mealType: ['Dessert'],
        ingredients: ['Khoya (milk solids) or Milk powder', 'All-purpose flour (Maida)', 'Sugar', 'Cardamom', 'Rose water', 'Ghee/Oil for frying'],
        instructions: 'Make dough with khoya/milk powder and flour. Shape into small balls. Fry until golden brown. Soak in warm sugar syrup flavored with cardamom and rose water.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/VVhs1wj9DhU?si=3_kirvXuTi5iHQeq" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 150, protein: 2, carbs: 20, fats: 7 } // per piece
    },
    {
        id: 'lassi',
        title: 'Mango Lassi',
        image: 'https://media.bluediamond.com/uploads/2023/01/24175942/14_Dairy-Free_Mango_Lassi-scaled.jpg',
        time: '10min',
        calories_text: '250 cal',
        rating: '4.8 ★',
        tags: ['Vegetarian', 'Indian', 'Beverage'],
        mealType: ['Beverage', 'Dessert', 'Snack'],
        ingredients: ['1 cup Yogurt (Dahi)', '1/2 cup Mango pulp/fresh mango', 'Sugar to taste', 'A pinch of Cardamom powder', 'Ice cubes (optional)'],
        instructions: 'Blend yogurt, mango pulp, sugar, and cardamom powder until smooth. Add ice cubes if desired and blend again. Serve chilled.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/vKn1b9G1BjE?si=e8AdsumTik3vaCDJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 250, protein: 8, carbs: 45, fats: 5 }
    },
    {
        id: 'pasta-carbonara',
        title: 'Pasta Carbonara',
        image: "https://static01.nyt.com/images/2021/02/14/dining/carbonara-horizontal/carbonara-horizontal-threeByTwoMediumAt2X-v2.jpg",
        time: '25min',
        calories_text: '600 cal',
        rating: '4.7 ★',
        tags: ['Non-Vegetarian', 'Italian'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Spaghetti', 'Eggs', 'Pancetta/Guanciale', 'Pecorino Romano cheese', 'Black pepper'],
        instructions: 'Cook pasta. Fry pancetta. Whisk eggs, cheese, pepper. Combine pasta with pancetta, then quickly stir in egg mixture off heat.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/D_2DBLAt57c?si=EviQuntTOwz5LVUV" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 600, protein: 25, carbs: 55, fats: 30 }
    },
    {
        id: 'margherita-pizza',
        title: 'Margherita Pizza',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPVKRyYZd-2Uzkavrzkbw8aZgzHOYqicnXBA&s",
        time: '30min + proofing',
        calories_text: '700 cal (whole)',
        rating: '4.8 ★',
        tags: ['Vegetarian', 'Italian'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Pizza dough', 'Tomato sauce (San Marzano)', 'Fresh mozzarella', 'Fresh basil', 'Olive oil'],
        instructions: 'Stretch dough. Top with sauce, mozzarella, basil. Drizzle olive oil. Bake in a very hot oven.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/vcfNpDtVqOw?si=_bK2Lts2pkZhuIz0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 700, protein: 28, carbs: 80, fats: 30 } // whole pizza
    },
    {
        id: 'sushi-rolls',
        title: 'Sushi Rolls (Maki)',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-SU9u7pqWZaw008hCWz0noS2iOk-Z_q6H4A&s",
        time: '1hr',
        calories_text: '300 cal (6 pieces)',
        rating: '4.6 ★',
        tags: ['Seafood', 'Japanese', 'Non-Vegetarian Option', 'Vegetarian Option'],
        mealType: ['Lunch', 'Dinner', 'Starter', 'Snack'],
        ingredients: ['Sushi rice', 'Nori sheets', 'Fillings (cucumber, avocado, salmon, tuna)', 'Soy sauce', 'Wasabi', 'Pickled ginger'],
        instructions: 'Prepare sushi rice. Lay nori on bamboo mat. Spread rice, add fillings. Roll tightly. Slice and serve.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/MMFIPJHHxjg?si=VaU4TcgusZxH1Mos" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 300, protein: 10, carbs: 50, fats: 8 } // 6 pieces
    },
    {
        id: 'pad-thai',
        title: 'Pad Thai',
        image: "https://mikhaeats.com/wp-content/uploads/2024/04/shrimp-pad-thai-featured-image-1-500x500.jpg",
        time: '30min',
        calories_text: '550 cal',
        rating: '4.7 ★',
        tags: ['Non-Vegetarian Option', 'Thai', 'Vegetarian Option'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Rice noodles', 'Shrimp/Chicken/Tofu', 'Eggs', 'Bean sprouts', 'Chives', 'Tamarind paste', 'Fish sauce', 'Sugar', 'Chili flakes', 'Peanuts'],
        instructions: 'Soak noodles. Stir-fry protein, add eggs. Add noodles and sauce. Toss with bean sprouts, chives. Garnish with peanuts, chili.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/b7YnoRFuZ9o?si=qRFKeQseGUl0ZvNX" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 550, protein: 25, carbs: 65, fats: 20 }
    },
    {
        id: 'tacos-al-pastor',
        title: 'Tacos al Pastor',
        image: "https://www.thespruceeats.com/thmb/wQd2RvxH1Lh9536W5LY1T_VSyT8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/tacos-al-pastor-recipe-4172074-hero-01-7fb1a4455397486b8485ac8ec2ca3c5a.jpg",
        time: '45min + marination',
        calories_text: '200 cal/taco',
        rating: '4.9 ★',
        tags: ['Non-Vegetarian', 'Mexican'],
        mealType: ['Lunch', 'Dinner', 'Snack', 'Street Food'],
        ingredients: ['Pork shoulder', 'Achiote paste', 'Chilies', 'Pineapple', 'Onion', 'Cilantro', 'Corn tortillas'],
        instructions: 'Marinate pork. Cook on a spit or pan-fry with pineapple. Serve on tortillas with onion, cilantro, and salsa.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/p1jieTUtMX4?si=gHKVLuUeBS_OqRU2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 200, protein: 10, carbs: 15, fats: 10 } // per taco
    },
    {
        id: 'greek-salad',
        title: 'Greek Salad (Horiatiki)',
        image: "https://www.simplyrecipes.com/thmb/0NrKQlJ691l6L9tZXpL06uOuWis=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Easy-Greek-Salad-LEAD-2-4601eff771fd4de38f9722e8cafc897a.jpg",
        time: '15min',
        calories_text: '300 cal',
        rating: '4.6 ★',
        tags: ['Vegetarian', 'Greek', 'Healthy'],
        mealType: ['Salad', 'Starter', 'Lunch', 'Side Dish'],
        ingredients: ['Tomatoes', 'Cucumbers', 'Red onion', 'Kalamata olives', 'Feta cheese', 'Olive oil', 'Oregano'],
        instructions: 'Chop vegetables. Combine in a bowl. Top with a block of feta, olives. Drizzle with olive oil and sprinkle oregano.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/T6-sIofa_4E?si=pJTUtpRm3RVbr1iu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 300, protein: 7, carbs: 10, fats: 25 }
    },
    {
        id: 'beef-stroganoff',
        title: 'Beef Stroganoff',
        image: "https://godairyfree.org/wp-content/uploads/2022/12/Beef-Stroganoff-online-feature2.jpg",
        time: '40min',
        calories_text: '580 cal',
        rating: '4.7 ★',
        tags: ['Non-Vegetarian', 'Russian'],
        mealType: ['Dinner', 'Main Course'],
        ingredients: ['Beef sirloin', 'Mushrooms', 'Onion', 'Sour cream', 'Beef broth', 'Mustard', 'Flour', 'Egg noodles'],
        instructions: 'Sear beef. Sauté onions, mushrooms. Make a roux, add broth. Stir in sour cream, mustard. Add beef. Serve over egg noodles.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/7r3dlmYUf4s?si=pfzN4k2DwOO3ptnO" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 580, protein: 30, carbs: 40, fats: 30 }
    },
    {
        id: 'croissant',
        title: 'Classic Croissant',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTT_r7XADNqlkLHUJM4UIV6UdWC-JFgcyXkwA&s",
        time: 'Multi-day process',
        calories_text: '300 cal/piece',
        rating: '4.9 ★',
        tags: ['Vegetarian', 'French', 'Bakery'],
        mealType: ['Breakfast', 'Brunch', 'Snack', 'Dessert'],
        ingredients: ['Flour', 'Butter (high fat)', 'Yeast', 'Sugar', 'Salt', 'Milk', 'Egg (for wash)'],
        instructions: 'Complex lamination process involving dough making, butter block, multiple folds and rests. Shape, proof, and bake.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/mT4cqHc4HqU?si=92wAg8_c-eX4eyWD" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 300, protein: 5, carbs: 30, fats: 18 } // per piece
    },
    {
        id: 'hummus',
        title: 'Hummus with Pita',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35ASfINgI7qVo8pYkLckdIqQpRw8CrENSww&s",
        time: '20min (if using canned chickpeas)',
        calories_text: '250 cal (serving)',
        rating: '4.7 ★',
        tags: ['Vegetarian', 'Middle Eastern', 'Vegan', 'Healthy'],
        mealType: ['Starter', 'Snack', 'Side Dish'],
        ingredients: ['Chickpeas', 'Tahini', 'Lemon juice', 'Garlic', 'Olive oil', 'Cumin', 'Pita bread'],
        instructions: 'Blend chickpeas, tahini, lemon juice, garlic, cumin, and a little water until smooth. Drizzle with olive oil. Serve with warm pita bread.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/V98MgC_MUUE?si=bGlak8SnUjl8L3R2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 250, protein: 8, carbs: 25, fats: 13 } // serving
    },
    {
        id: 'shepherds-pie',
        title: "Shepherd's Pie",
        image: "https://www.homecookingadventure.com/wp-content/uploads/2022/01/shepherds_pie_main.jpg ",
        time: '1hr',
        calories_text: '550 cal',
        rating: '4.6 ★',
        tags: ['Non-Vegetarian', 'British', 'Irish'],
        mealType: ['Dinner', 'Main Course'],
        ingredients: ['Ground lamb (or beef for Cottage Pie)', 'Onion', 'Carrots', 'Peas', 'Beef broth', 'Worcestershire sauce', 'Mashed potatoes', 'Cheese (optional)'],
        instructions: 'Cook meat and vegetable filling. Top with mashed potatoes (and cheese). Bake until golden.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/Uj8BC2kcp7A?si=Ip-2N0Zk4KOf0I3p" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 550, protein: 28, carbs: 45, fats: 28 }
    },
    {
        id: 'caesar-salad',
        title: 'Caesar Salad',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0zzKsmxNQvdw61jTeEoz3kTFZAG055ASulw&s",
        time: '25min',
        calories_text: '450 cal',
        rating: '4.5 ★',
        tags: ['Non-Vegetarian Option', 'American', 'Salad'],
        mealType: ['Lunch', 'Salad', 'Starter', 'Brunch'],
        ingredients: ['Romaine lettuce', 'Croutons', 'Parmesan cheese', 'For dressing: Egg yolk, Anchovies, Garlic, Dijon mustard, Lemon juice, Olive oil', 'Grilled chicken (optional)'],
        instructions: 'Make Caesar dressing. Toss with romaine lettuce, croutons, and Parmesan. Top with grilled chicken if desired.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/IGlWE4AFQ5Q?si=PMNUn97qCG0inDL5" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 450, protein: 20, carbs: 10, fats: 35 } // with chicken, can vary a lot
    },
    {
        id: 'chocolate-chip-cookies',
        title: 'Chocolate Chip Cookies',
        image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2014/7/17/1/FN_Simple-Chocolate-Chip-Cookies_s4x3.jpg.rend.hgtvcom.1280.960.suffix/1438794106265.webp",
        time: '30min + chilling',
        calories_text: '150 cal/cookie',
        rating: '4.9 ★',
        tags: ['Vegetarian', 'American', 'Dessert', 'Bakery'],
        mealType: ['Dessert', 'Snack'],
        ingredients: ['Flour', 'Butter', 'Brown sugar', 'Granulated sugar', 'Eggs', 'Vanilla extract', 'Baking soda', 'Salt', 'Chocolate chips'],
        instructions: 'Cream butter and sugars. Beat in eggs, vanilla. Combine dry ingredients, add to wet. Stir in chocolate chips. Chill dough. Scoop and bake.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/fEl7_ti9_pQ?si=Tt9DgD0RMTEc3mf_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 150, protein: 2, carbs: 20, fats: 8 } // per cookie
    },
    {
        id: 'poha',
        title: 'Poha',
        image: "https://www.ohmyveg.co.uk/wp-content/webp-express/webp-images/uploads/2023/09/Poha-4-copy-3-e1722868478363-768x768.jpg.webp",
        time: '20min',
        calories_text: '250 cal',
        rating: '4.6 ★',
        tags: ['Vegetarian', 'Indian', 'Breakfast', 'Vegan'],
        mealType: ['Breakfast', 'Brunch', 'Snack'],
        ingredients: ['Flattened rice (poha)', 'Onion', 'Mustard seeds', 'Turmeric', 'Peanuts', 'Lemon'],
        instructions: 'Rinse poha. Temper spices, sauté onion. Add poha, peanuts. Garnish.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/XuttnylxuXY?si=mJKREsNn_IFAk9CL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 250, protein: 5, carbs: 45, fats: 5 }
    },
    {
        id: 'upma',
        title: 'Upma',
        image: "https://thewhiskaddict.com/wp-content/uploads/2024/07/IMG_0332-768x1152.jpg",
        time: '25min',
        calories_text: '300 cal',
        rating: '4.5 ★',
        tags: ['Vegetarian', 'Indian', 'Breakfast', 'Vegan Option'],
        mealType: ['Breakfast', 'Brunch'],
        ingredients: ['Semolina (rava/suji)', 'Onion', 'Mustard seeds', 'Vegetables (carrot, peas)', 'Curry leaves'],
        instructions: 'Roast semolina. Temper spices, sauté onion, veg. Add water, then semolina. Cook.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/CTEs7hS99Ws?si=0FWCfqKVUBvy1Os6" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 300, protein: 7, carbs: 50, fats: 8 }
    },
    {
        id: 'aloo-paratha',
        title: 'Aloo Paratha',
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Aloo_Paratha_also_known_as_Batatay_Jo_Phulko.jpg/500px-Aloo_Paratha_also_known_as_Batatay_Jo_Phulko.jpg",
        time: '45min',
        calories_text: '350 cal/pc',
        rating: '4.8 ★',
        tags: ['Vegetarian', 'Indian', 'Punjabi'],
        mealType: ['Breakfast', 'Brunch', 'Lunch'],
        ingredients: ['Whole wheat flour', 'Potatoes (boiled, mashed)', 'Spices', 'Ghee/Oil'],
        instructions: 'Make dough & spiced potato filling. Stuff, roll, cook on tawa with ghee.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/j3pDXY9fqSo?si=PowcnvgcZXJhR8TS" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 350, protein: 8, carbs: 50, fats: 12 } // per piece
    },
    {
        id: 'gobi-paratha',
        title: 'Gobi Paratha',
        image: "https://vismaifood.com/storage/app/uploads/public/495/d73/0c7/thumb__700_0_0_0_auto.jpg",
        time: '50min',
        calories_text: '320 cal/pc',
        rating: '4.7 ★',
        tags: ['Vegetarian', 'Indian', 'Punjabi'],
        mealType: ['Breakfast', 'Brunch', 'Lunch'],
        ingredients: ['Whole wheat flour', 'Cauliflower (grated)', 'Spices', 'Ghee/Oil'],
        instructions: 'Make dough & spiced cauliflower filling. Stuff, roll, cook on tawa.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/nR5ndiOwupY?si=sQ4Y2SmKeaV9K55Z" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 320, protein: 7, carbs: 45, fats: 13 } // per piece
    },
    {
        id: 'chole-bhature',
        title: 'Chole Bhature',
        image: "https://i.ytimg.com/vi/csfIOfMnRGg/hqdefault.jpg",
        time: '1hr + ferment',
        calories_text: '600 cal',
        rating: '4.9 ★',
        tags: ['Vegetarian', 'Indian', 'Punjabi'],
        mealType: ['Brunch', 'Lunch', 'Dinner', 'Main Course', 'Street Food'],
        ingredients: ['Chickpeas (chole)', 'Flour (for bhature)', 'Yogurt', 'Spices'],
        instructions: 'Cook chole curry. Make dough for bhature, ferment, deep fry.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/aFzBnNWEu5Y?si=RTJZk574UckYILQX" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 600, protein: 15, carbs: 80, fats: 25 }
    },
    {
        id: 'dhokla',
        title: 'Khaman Dhokla',
        image: "https://bhojmasale.com/cdn/shop/articles/instant-easiest-khaman-dhokla-recipe-268336_1024x1024.jpg?v=1739153038",
        time: '30min + ferment',
        calories_text: '150 cal',
        rating: '4.7 ★',
        tags: ['Vegetarian', 'Indian', 'Gujarati', 'Snack', 'Vegan'],
        mealType: ['Snack', 'Starter', 'Breakfast'],
        ingredients: ['Gram flour (besan)', 'Yogurt/Citric acid', 'Eno/Fruit salt', 'Tempering (mustard, sesame, curry leaves)'],
        instructions: 'Make batter, ferment. Steam. Top with tempering.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/TEGPt00TQxM?si=91O1wLQPJQ539kvL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 150, protein: 6, carbs: 25, fats: 3 } // per serving
    },
    {
        id: 'khandvi',
        title: 'Khandvi',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6MkXTRrBfliLH0jbWjTCPvlkI3cFc6au39Q&s",
        time: '45min',
        calories_text: '200 cal',
        rating: '4.6 ★',
        tags: ['Vegetarian', 'Indian', 'Gujarati', 'Snack'],
        mealType: ['Snack', 'Starter'],
        ingredients: ['Gram flour (besan)', 'Yogurt', 'Ginger-chili paste', 'Tempering'],
        instructions: 'Cook besan-yogurt mixture till thick. Spread thin, roll. Top with tempering.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/IQRxNePeLo8?si=4rEYd7FEkp9uAsHl" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 200, protein: 8, carbs: 20, fats: 10 } // per serving
    },
    {
        id: 'hyderabadi-biryani',
        title: 'Hyderabadi Chicken Biryani',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTlJnprTaakbTI0kzZAqgw_Ugn8-Wn4d6u4g&s",
        time: '1hr 30min + marinate',
        calories_text: '650 cal',
        rating: '4.9 ★',
        tags: ['Non-Vegetarian', 'Indian', 'Hyderabadi'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Basmati rice', 'Chicken', 'Yogurt', 'Spices', 'Mint', 'Coriander', 'Fried onions'],
        instructions: 'Marinate chicken. Layer with partially cooked rice, herbs, fried onions. Dum cook.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/aleED1mc5kI?si=I2ZdN9Hr8ien3lL2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 650, protein: 35, carbs: 70, fats: 25 }
    },
    {
        id: 'mysore-pak',
        title: 'Mysore Pak',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbxdTqW7aXxcyBB6kpksFNvFfRxdQuHoQA-A&s",
        time: '40min',
        calories_text: '300 cal/pc',
        rating: '4.7 ★',
        tags: ['Vegetarian', 'Indian', 'Dessert', 'South Indian'],
        mealType: ['Dessert'],
        ingredients: ['Gram flour (besan)', 'Ghee', 'Sugar'],
        instructions: 'Roast besan. Make sugar syrup. Add besan, then ghee gradually. Set & cut.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/Np2jiYSd6aE?si=VU4bps3HCpUYP1qU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 300, protein: 3, carbs: 40, fats: 15 } // per piece
    },
    {
        id: 'rasgulla',
        title: 'Rasgulla',
        image: "https://cdn.ready-market.com.tw/21cd62de/Templates/pic/ANKO-Rasgulla-1200X1200.jpg?v=1a046a18",
        time: '1hr',
        calories_text: '100 cal/pc',
        rating: '4.8 ★',
        tags: ['Vegetarian', 'Indian', 'Dessert', 'Bengali'],
        mealType: ['Dessert'],
        ingredients: ['Chenna (milk solids)', 'Sugar', 'Cardamom'],
        instructions: 'Make chenna balls. Cook in light sugar syrup until spongy.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/dd9_YZdQS0c?si=iqXABsRe79gLRjDc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 100, protein: 2, carbs: 20, fats: 1 } // per piece
    },
    {
        id: 'jalebi',
        title: 'Jalebi',
        image: "https://images.slurrp.com/prod/recipe_images/better-butter/crispy-jalebi_50KFDO0XHO2I7S9X7VJ6.webp",
        time: '45min + ferment',
        calories_text: '150 cal/pc',
        rating: '4.9 ★',
        tags: ['Vegetarian', 'Indian', 'Dessert'],
        mealType: ['Dessert', 'Snack', 'Street Food'],
        ingredients: ['Flour', 'Yogurt', 'Sugar', 'Saffron', 'Ghee/Oil for frying'],
        instructions: 'Make batter, ferment. Pipe spirals into hot oil. Soak in sugar syrup.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/hgwdaU-K5wk?si=e6eV0oipgfPkVsoD" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 150, protein: 1, carbs: 25, fats: 5 } // per piece
    },
    {
        id: 'palak-dal',
        title: 'Dal Palak (Spinach Dal)',
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/09/dal-palak-spinach-dal.jpg",
        time: '35min',
        calories_text: '300 cal',
        rating: '4.6 ★',
        tags: ['Vegetarian', 'Indian', 'Vegan'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Lentils (toor/moong)', 'Spinach', 'Onion', 'Tomato', 'Spices'],
        instructions: 'Cook dal. Sauté onion, tomato, spices. Add spinach & cooked dal. Simmer.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/3xr76O6wmdM?si=BhbbvIGRPHCBthJ7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 300, protein: 15, carbs: 40, fats: 10 }
    },
    {
        id: 'methi-chicken',
        title: 'Methi Chicken (Fenugreek Chicken)',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE5ltLA9qWcGh5thxuV09OkI8U8aIzNFtaQw&s",
        time: '50min',
        calories_text: '450 cal',
        rating: '4.7 ★',
        tags: ['Non-Vegetarian', 'Indian'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Chicken', 'Fresh fenugreek leaves (methi)', 'Onion', 'Tomato', 'Yogurt', 'Spices'],
        instructions: 'Sauté chicken with spices. Add methi leaves, yogurt, tomato. Cook till done.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/-aRI8Brpwqo?si=pgkFw7Sd5GVK1Vxw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 450, protein: 35, carbs: 15, fats: 28 }
    },
    {
        id: 'keema-pav',
        title: 'Keema Pav',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQj-sVVivjoT5ZSc99ruGXX9lg5SEsPuJsG1w&s",
        time: '1hr',
        calories_text: '500 cal',
        rating: '4.8 ★',
        tags: ['Non-Vegetarian', 'Indian', 'Street Food'],
        mealType: ['Lunch', 'Dinner', 'Snack', 'Street Food'],
        ingredients: ['Minced meat (lamb/chicken)', 'Onion', 'Tomato', 'Ginger-garlic', 'Spices', 'Peas', 'Pav'],
        instructions: 'Cook minced meat with spices, onion, tomato, peas. Serve with pav.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/Tjzar3cktro?si=d5Tdjv5vqBc6CupE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 500, protein: 25, carbs: 40, fats: 25 }
    },
    {
        id: 'fish-fry-indian',
        title: 'Indian Fish Fry',
        image: "https://www.spiceindiaonline.com/wp-content/uploads/2017/04/Meen-Varuval-Tilapia-Fish-Fry-2.jpg",
        time: '30min + marinate',
        calories_text: '380 cal',
        rating: '4.7 ★',
        tags: ['Non-Vegetarian', 'Indian'],
        mealType: ['Starter', 'Side Dish', 'Lunch', 'Dinner'],
        ingredients: ['Fish fillets', 'Ginger-garlic paste', 'Chili powder', 'Turmeric', 'Gram flour', 'Lemon juice'],
        instructions: 'Marinate fish with spices. Shallow fry or deep fry until crisp.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/nF_YvdSWVZc?si=nM7W5FSORnvNk_A9" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 380, protein: 22, carbs: 10, fats: 28 }
    },
    {
        id: 'prawn-curry',
        title: 'Prawn Curry',
        image: "https://i.ytimg.com/vi/aAy3nW9SiPA/maxresdefault.jpg",
        time: '40min',
        calories_text: '420 cal',
        rating: '4.8 ★',
        tags: ['Non-Vegetarian', 'Indian', 'Coastal'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Prawns', 'Coconut milk', 'Onion', 'Tomato', 'Ginger-garlic', 'Spices'],
        instructions: 'Make curry base with coconut milk, onion, tomato, spices. Add prawns & cook.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/_g9RiFvg7cs?si=_ytQloqFijLNYjIs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 420, protein: 25, carbs: 15, fats: 30 }
    },
    {
        id: 'shahi-paneer',
        title: 'Shahi Paneer',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaqqfgLb7Wpyk-NMRCh-0p_oFLsiZZzzvOLw&s',
        time: '45min',
        calories_text: '480 cal',
        rating: '4.8 ★',
        tags: ['Vegetarian', 'Indian', 'Mughlai'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Paneer', 'Onion', 'Cashews', 'Almonds', 'Cream', 'Yogurt', 'Spices'],
        instructions: 'Make rich, creamy, nutty gravy. Add paneer cubes. Simmer.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/tgw4uYyqqi8?si=Lta6CXhrVYWjUyHm" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 480, protein: 18, carbs: 20, fats: 38 }
    },
    {
        id: 'navratan-korma',
        title: 'Navratan Korma',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOlSnqdE1oyBBGzVN84tRoPIz5sEBoEk-7Jg&s",
        time: '50min',
        calories_text: '450 cal',
        rating: '4.7 ★',
        tags: ['Vegetarian', 'Indian', 'Mughlai'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Mixed vegetables (9 types)', 'Paneer', 'Nuts', 'Cream', 'Spices'],
        instructions: 'Make a mild, creamy korma gravy. Add blanched vegetables, paneer, nuts.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/thwoxZYf9x0?si=KqnlwWzPAiGX7aRW" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 450, protein: 12, carbs: 30, fats: 32 }
    },
    {
        id: 'veg-jalfrezi',
        title: 'Vegetable Jalfrezi',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbvATuQ6ZshaJChD-A82J5PTX0JrrCU9x_lA&s',
        time: '35min',
        calories_text: '320 cal',
        rating: '4.6 ★',
        tags: ['Vegetarian', 'Indian', 'Vegan'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Mixed vegetables (bell peppers, onion, tomato, carrot)', 'Paneer (opt)', 'Spices'],
        instructions: 'Stir-fry vegetables with spices in a tangy tomato-based sauce.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/NrYmeJSNmVU?si=kcpy4YA4560NP5KP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 320, protein: 8, carbs: 35, fats: 18 }
    },
    {
        id: 'kheer',
        title: 'Kheer (Rice Pudding)',
        image: "https://www.honeywhatscooking.com/wp-content/uploads/2020/10/Rice-Kheer-Indian-Rice-Pudding44.jpg",
        time: '45min',
        calories_text: '350 cal',
        rating: '4.8 ★',
        tags: ['Vegetarian', 'Indian', 'Dessert'],
        mealType: ['Dessert'],
        ingredients: ['Rice', 'Milk', 'Sugar', 'Cardamom', 'Nuts', 'Saffron (opt)'],
        instructions: 'Cook rice in milk until creamy. Add sugar, cardamom, nuts. Simmer.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/878WHgjtoMo?si=WqPWePlOvKVIl8_m" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 350, protein: 7, carbs: 60, fats: 10 }
    },
    {
        id: 'french-onion-soup',
        title: 'French Onion Soup',
        image: "https://www.fearlessdining.com/wp-content/uploads/2023/03/Gluten-Free-French-Onion-Soup-1200-hero.jpg",
        time: '1hr 30min',
        calories_text: '400 cal',
        rating: '4.7 ★',
        tags: ['French', 'Soup'],
        mealType: ['Soup', 'Starter', 'Lunch'],
        ingredients: ['Onions', 'Beef broth', 'Butter', 'Flour', 'Baguette', 'Gruyère cheese'],
        instructions: 'Caramelize onions deeply. Make broth. Top with bread & cheese, broil.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/1qRir364aNk?si=veVeF2J8cIrz_VF2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 400, protein: 15, carbs: 30, fats: 22 }
    },
    {
        id: 'ratatouille',
        title: 'Ratatouille',
        image: "https://plantbasedonabudget.com/wp-content/uploads/2021/07/FullSizeRender-47.jpg",
        time: '1hr 15min',
        calories_text: '250 cal',
        rating: '4.6 ★',
        tags: ['Vegetarian', 'French', 'Vegan', 'Healthy'],
        mealType: ['Lunch', 'Dinner', 'Side Dish', 'Main Course'],
        ingredients: ['Eggplant', 'Zucchini', 'Bell peppers', 'Tomatoes', 'Onion', 'Garlic', 'Herbs de Provence'],
        instructions: 'Sauté or bake layered vegetables with herbs and tomato sauce.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/RQlp-p_Qcsw?si=n3lKDCZ4DOX04CzD" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 250, protein: 5, carbs: 30, fats: 12 }
    },
    {
        id: 'beef-bourguignon',
        title: 'Beef Bourguignon',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ10UJBpX_jPj7GFHumUsOZtNG5qridHKS1oA&s",
        time: '3-4 hrs',
        calories_text: '650 cal',
        rating: '4.9 ★',
        tags: ['Non-Vegetarian', 'French', 'Stew'],
        mealType: ['Dinner', 'Main Course'],
        ingredients: ['Beef chuck', 'Red wine (Burgundy)', 'Bacon', 'Mushrooms', 'Onions', 'Carrots', 'Beef broth'],
        instructions: 'Slow-cook beef in red wine with vegetables and aromatics until very tender.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/_Bx9P32tdaM?si=_H4Z5kJeV9_Yyqtw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 650, protein: 45, carbs: 20, fats: 35 }
    },
    {
        id: 'lasagna-bolognese',
        title: 'Lasagna Bolognese',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSsuTC2KKzdc4Zsq4bQtmQBSIs1jHbW7LgJA&s",
        time: '2hrs',
        calories_text: '700 cal',
        rating: '4.8 ★',
        tags: ['Non-Vegetarian', 'Italian'],
        mealType: ['Dinner', 'Main Course'],
        ingredients: ['Lasagna pasta', 'Bolognese sauce (meat ragu)', 'Béchamel sauce', 'Parmesan cheese'],
        instructions: 'Layer pasta, Bolognese, béchamel, and Parmesan. Bake until bubbly.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/xIQXLTFup6M?si=CNmoL4EIu9UMbzui" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 700, protein: 35, carbs: 60, fats: 35 }
    },
    {
        id: 'mushroom-risotto',
        title: 'Mushroom Risotto',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi_xl2cUZebHKvHamemJ8g2fCBYeNjcIcQSQ&s",
        time: '45min',
        calories_text: '500 cal',
        rating: '4.7 ★',
        tags: ['Vegetarian', 'Italian'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Arborio rice', 'Mushrooms (porcini, cremini)', 'Vegetable broth', 'Onion', 'White wine', 'Parmesan cheese', 'Butter'],
        instructions: 'Sauté mushrooms. Toast rice. Gradually add hot broth, stirring constantly. Finish with cheese & butter.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/8ak3lUxy_yU?si=e2DY8fS447tzgO-X" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 500, protein: 15, carbs: 60, fats: 20 }
    },
    {
        id: 'gazpacho',
        title: 'Gazpacho',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6l0So5h8udvkoR519JWwXCf3QyychDiYiuQ&s",
        time: '20min + chill',
        calories_text: '150 cal',
        rating: '4.5 ★',
        tags: ['Vegetarian', 'Spanish', 'Soup', 'Vegan', 'Healthy'],
        mealType: ['Soup', 'Starter', 'Lunch'],
        ingredients: ['Tomatoes', 'Cucumber', 'Bell pepper', 'Onion', 'Garlic', 'Olive oil', 'Vinegar', 'Bread (opt)'],
        instructions: 'Blend raw vegetables until smooth. Chill well. Garnish and serve.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/pXBPKXm4T1U?si=xsbMKe0-hbv-DUzp" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 150, protein: 3, carbs: 20, fats: 7 }
    },
    {
        id: 'falafel-pita',
        title: 'Falafel in Pita',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-tkVtkksuD8avASAZ_LWt8Z4zN_YhjpSqKw&s",
        time: '45min + soak',
        calories_text: '400 cal',
        rating: '4.7 ★',
        tags: ['Vegetarian', 'Middle Eastern', 'Vegan'],
        mealType: ['Lunch', 'Snack', 'Starter', 'Street Food'],
        ingredients: ['Chickpeas (dried)', 'Herbs (parsley, cilantro)', 'Spices', 'Onion', 'Garlic', 'Pita bread', 'Tahini sauce', 'Salad'],
        instructions: 'Grind soaked chickpeas with herbs & spices. Form patties/balls, fry. Serve in pita with sauce & salad.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/Q6udZLwaYG8?si=yb4jrgAWjdln8Fgq" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 400, protein: 12, carbs: 50, fats: 18 }
    },
    {
        id: 'shakshuka',
        title: 'Shakshuka',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxs_UIIDubbgfpnelYasMqhMOFTgYVSaG51A&s",
        time: '30min',
        calories_text: '350 cal',
        rating: '4.8 ★',
        tags: ['Vegetarian', 'Middle Eastern', 'North African', 'Breakfast'],
        mealType: ['Breakfast', 'Brunch', 'Lunch'],
        ingredients: ['Eggs', 'Tomatoes (canned or fresh)', 'Onion', 'Bell pepper', 'Garlic', 'Spices (cumin, paprika)', 'Feta (opt)'],
        instructions: 'Simmer vegetables in spiced tomato sauce. Crack eggs into sauce. Cook until eggs are set.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/VNW2_ndBWYg?si=B4QwVTvZuKGuyWmx" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 350, protein: 18, carbs: 20, fats: 22 }
    },
    {
        id: 'kimchi-fried-rice',
        title: 'Kimchi Fried Rice',
        image: 'https://takestwoeggs.com/wp-content/uploads/2022/03/Kimchi-Fried-Rice-Kimchi-bokkeumbap-takestwoeggs-final-photography-sq.jpg',
        time: '20min',
        calories_text: '450 cal',
        rating: '4.7 ★',
        tags: ['Korean', 'Non-Vegetarian Option', 'Spicy'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Cooked rice (day-old)', 'Kimchi', 'Gochujang (Korean chili paste)', 'Pork/Tofu (opt)', 'Egg (fried)', 'Sesame oil', 'Seaweed'],
        instructions: 'Stir-fry kimchi & protein. Add rice, gochujang, kimchi juice. Top with fried egg & seaweed.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/pr-uZxNkjYk?si=mGt4nLUc7wL0R62G" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 450, protein: 15, carbs: 60, fats: 18 } // Can vary with protein choice
    },
    {
        id: 'bibimbap',
        title: 'Bibimbap',
        image: 'https://eggs.ca/wp-content/uploads/2024/06/EFC-BIBIMBAP-1280x720-1.jpg',
        time: '45min',
        calories_text: '550 cal',
        rating: '4.8 ★',
        tags: ['Korean', 'Non-Vegetarian Option', 'Vegetarian Option'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Cooked rice', 'Assorted seasoned vegetables (spinach, carrots, bean sprouts)', 'Beef/Tofu', 'Egg (fried)', 'Gochujang sauce'],
        instructions: 'Arrange rice, vegetables, protein in a bowl. Top with egg & serve with gochujang.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/lqUtV6lT1n4?si=yHIwkEGeA7NfUrRJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 550, protein: 25, carbs: 70, fats: 18 } // Can vary with protein choice
    },
    {
        id: 'thai-green-curry',
        title: 'Thai Green Curry',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHds5Udo06toWjsRQiEybmlW6ztGIE3skfXA&s",
        time: '35min',
        calories_text: '500 cal',
        rating: '4.7 ★',
        tags: ['Thai', 'Spicy', 'Non-Vegetarian Option'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Chicken/Tofu', 'Green curry paste', 'Coconut milk', 'Vegetables (bamboo shoots, bell pepper, eggplant)', 'Fish sauce', 'Basil'],
        instructions: 'Sauté curry paste. Add coconut milk, protein, vegetables. Simmer. Finish with fish sauce & basil.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/-zeV6vSS0mk?si=rdQYdxq1vTPPKRZ9" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 500, protein: 28, carbs: 25, fats: 30 } // With chicken
    },
    {
        id: 'tom-yum-soup',
        title: 'Tom Yum Soup',
        image: "https://cicili.tv/wp-content/uploads/2021/10/Tom-Yum-Goong-1-scaled.jpg",
        time: '30min',
        calories_text: '200 cal',
        rating: '4.6 ★',
        tags: ['Thai', 'Soup', 'Spicy', 'Seafood Option'],
        mealType: ['Soup', 'Starter', 'Lunch'],
        ingredients: ['Shrimp/Chicken', 'Lemongrass', 'Galangal', 'Kaffir lime leaves', 'Chilies', 'Mushrooms', 'Fish sauce', 'Lime juice'],
        instructions: 'Simmer aromatics in broth. Add protein, mushrooms. Season with fish sauce, lime juice, chilies.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/QyWdCbgQf84?si=X5cSWbFX-cqbBR-_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 200, protein: 15, carbs: 15, fats: 8 } // With shrimp
    },
    {
        id: 'pho-bo',
        title: 'Pho (Beef Noodle Soup)',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRytzvqiWmRe11mLZbArFEt2BiJ-t-NXTdnrA&s",
        time: 'Long broth / 30min assemble',
        calories_text: '450 cal',
        rating: '4.8 ★',
        tags: ['Vietnamese', 'Soup', 'Non-Vegetarian'],
        mealType: ['Soup', 'Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Rice noodles', 'Beef bones (for broth)', 'Beef (thinly sliced raw & cooked)', 'Spices (star anise, cinnamon)', 'Herbs (basil, cilantro, mint)', 'Bean sprouts', 'Lime'],
        instructions: 'Prepare rich spiced beef broth. Assemble bowl with noodles, beef, herbs. Pour hot broth over.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/9Sg21AHuO4A?si=aYVSkY-krOUmDx4d" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 450, protein: 30, carbs: 50, fats: 15 }
    },
    {
        id: 'spring-rolls-fresh',
        title: 'Fresh Spring Rolls (Goi Cuon)',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOBKa1yC5jjIaMUsfxoOh8lT1JkBPL3KFOmg&s",
        time: '40min',
        calories_text: '100 cal/roll',
        rating: '4.7 ★',
        tags: ['Vietnamese', 'Healthy', 'Non-Vegetarian Option', 'Vegan Option'],
        mealType: ['Starter', 'Snack', 'Lunch'],
        ingredients: ['Rice paper wrappers', 'Cooked shrimp/Tofu', 'Rice vermicelli noodles', 'Lettuce', 'Mint', 'Cilantro', 'Carrot', 'Cucumber', 'Peanut dipping sauce'],
        instructions: 'Soften rice paper. Fill with noodles, protein, herbs, vegetables. Roll tightly. Serve with sauce.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/JTtp-nHHvuc?si=Yo-1q4RnxzZVQvCs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 100, protein: 5, carbs: 15, fats: 2 } // per roll, varies with filling
    },
    {
        id: 'dim-sum-siu-mai',
        title: 'Siu Mai (Pork & Shrimp Dumplings)',
        image: "https://redhousespice.com/wp-content/uploads/2022/11/dim-sum-siu-mai-scaled.jpg",
        time: '1hr',
        calories_text: '70 cal/pc',
        rating: '4.7 ★',
        tags: ['Chinese', 'Dim Sum', 'Non-Vegetarian'],
        mealType: ['Starter', 'Snack', 'Brunch'],
        ingredients: ['Ground pork', 'Shrimp', 'Wonton wrappers', 'Mushrooms', 'Water chestnuts', 'Soy sauce', 'Sesame oil'],
        instructions: 'Mix filling ingredients. Wrap in wonton skins (open top). Steam until cooked.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/thRXxfLn-Rw?si=0zQYZO25kSeNkbiZ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 70, protein: 5, carbs: 3, fats: 4 } // per piece
    },
    {
        id: 'kung-pao-chicken',
        title: 'Kung Pao Chicken',
        image: "https://assets.tmecosys.com/image/upload/t_web_rdp_recipe_584x480/img/recipe/ras/Assets/188353BD-9C50-4D76-86E6-A45F525119CF/Derivates/71FB3CEC-4C97-479C-8D6B-354B4EFB513E.jpg",
        time: '30min',
        calories_text: '500 cal',
        rating: '4.6 ★',
        tags: ['Chinese', 'Non-Vegetarian', 'Spicy'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['Chicken (diced)', 'Peanuts', 'Dried chilies', 'Bell peppers', 'Soy sauce', 'Vinegar', 'Sugar', 'Cornstarch', 'Sichuan peppercorns'],
        instructions: 'Marinate chicken. Stir-fry chicken, then add chilies, peanuts, vegetables. Add sauce & thicken.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/YT8oN4U7Vm8?si=1uDjszHRlSFeVCO1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 500, protein: 30, carbs: 25, fats: 30 }
    },
    {
        id: 'fish-and-chips',
        title: 'Fish and Chips',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRq8w6_nexyYSWS6j0XoPCCOgr1xjzlekOAUg&s",
        time: '45min',
        calories_text: '800 cal',
        rating: '4.7 ★',
        tags: ['British', 'Seafood', 'Non-Vegetarian'],
        mealType: ['Lunch', 'Dinner', 'Main Course'],
        ingredients: ['White fish fillets (cod, haddock)', 'Flour', 'Beer (for batter)', 'Potatoes (for chips)', 'Oil for frying', 'Tartar sauce', 'Lemon'],
        instructions: 'Make batter. Dip fish, deep fry. Cut potatoes into chips, deep fry. Serve with tartar sauce & lemon.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/zit9l5jtbws?si=CrUaibVSherzA9NL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 800, protein: 25, carbs: 70, fats: 45 }
    },
    {
        id: 'apple-pie',
        title: 'Classic Apple Pie',
        image: "https://www.southernliving.com/thmb/bbDY1d_ySIrCFcq8WNBkR-3x6pU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/2589601_Mailb_Mailbox_Apple_Pie_003-da802ff7a8984b2fa9aa0535997ab246.jpg",
        time: '1hr 30min + chill',
        calories_text: '400 cal/slice',
        rating: '4.8 ★',
        tags: ['American', 'European', 'Dessert', 'Vegetarian'],
        mealType: ['Dessert'],
        ingredients: ['Pie crust (shortcrust pastry)', 'Apples (Granny Smith, Honeycrisp)', 'Sugar', 'Cinnamon', 'Nutmeg', 'Butter', 'Lemon juice'],
        instructions: 'Make pie crust. Prepare spiced apple filling. Assemble pie (bottom crust, filling, top crust/lattice). Bake until golden.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/4-bN7_fGwv4?si=GI6GdGji9tYmfpi8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 400, protein: 3, carbs: 55, fats: 20 } // per slice
    },
    {
        id: 'brownies-fudgy',
        title: 'Fudgy Chocolate Brownies',
        image: "https://www.allrecipes.com/thmb/clZmX6t75JnKN3MXtYvc-nOKiNE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/16722-fudgy-brownies-ddmfs-4x3_6682-3e3d2d1bd21e41169a7c86b44dc8c2d0.jpg",
        time: '45min',
        calories_text: '250 cal/pc',
        rating: '4.9 ★',
        tags: ['American', 'Dessert', 'Vegetarian', 'Chocolate'],
        mealType: ['Dessert', 'Snack'],
        ingredients: ['Chocolate (dark/bittersweet)', 'Butter', 'Sugar', 'Eggs', 'Flour', 'Cocoa powder', 'Vanilla extract', 'Salt'],
        instructions: 'Melt chocolate & butter. Mix with sugar, eggs, vanilla. Fold in dry ingredients. Bake.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/Z1OLG7F3HD4?si=nW50_E8GXrvvxjHW" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 250, protein: 3, carbs: 30, fats: 15 } // per piece
    },
    {
        id: 'crepes-suzette',
        title: 'Crepes Suzette',
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCpzeJ7G-XImx4acr1YXyuyPr26_sDdDXY4g&s",
        time: '40min',
        calories_text: '350 cal',
        rating: '4.7 ★',
        tags: ['French', 'Dessert', 'Vegetarian'],
        mealType: ['Dessert', 'Brunch'],
        ingredients: ['For crepes: Flour, Eggs, Milk, Sugar, Butter', 'For sauce: Butter, Sugar, Orange juice, Orange zest, Grand Marnier (optional)'],
        instructions: 'Make thin crepes. Prepare orange butter sauce (Suzette sauce). Fold crepes, simmer in sauce. Flambé if desired.',
        videoEmbed: '<iframe width="560" height="315" src="https://www.youtube.com/embed/XiG5Dvn0U3A?si=YDWRaeFFL6allxsF" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        nutrition: { calories: 350, protein: 6, carbs: 40, fats: 18 }
    }
];